p1 = Pattern.create(name: "Bubble Caddis", category: "Dry Fly")
p2 = Pattern.create(name: "Stonefly", category: "Nymph")
p3 = Pattern.create(name: "Clouser Minnow", category: "Streamer")

# m1 = Material.create(name: "Hook", description: "Size 14")
# m2 = Material.create(name: "Hook", description: "Size 8")
# m3 = Material.create(name: "Hook", description: "Size 4")


# m4 = Material.create(name: "Saddle Hackle", description: "Grizzly")
# m5 = Material.create(name: "Maribou", description: "Olive")
# m6 = Material.create(name: "Dubbing", description: "Black")
# m7 = Material.create(name: "Copper Wire", description: ".05")
# m8 = Material.create(name: "Lead Wire", description: ".025")
# m9 = Material.create(name: "Deer Hair", description: "Natural")
# m10 = Material.create(name: "Buck Tail", description: "Chartreuse")
# m11 = Material.create(name: "Thread", description: "Black")
# m12 = Material.create(name: "Thread", description: "Olive")
# m13 = Material.create(name: "Elk Hair", description: "Bleached")
# m14 = Material.create(name: "Dubbing", description: "Olive")
# m15 = Material.create(name: "Foam", description: "Yellow")
# m16 = Material.create(name: "Dumbell Eyes", description: "Red")
# m17 = Material.create(name: "Thread", description: "White")
# m18 = Material.create(name: "Maribou", description: "Blace")
# m19 = Material.create(name: "Peacock", description: "Sword")

